server:
  port: 8001
spring:
  profiles:
    active: dev #默认为开发环境

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.uzykj.fpsso: debug



mybatis:
  type-aliases-package: com.uzykj.fpocr.mapper
  mapper-locations: classpath:mapper/*.xml


md5:
  secret: uzyfp
  version: uzykj_1