app:
  id: fp-admin
# apollo配置
apollo:
  bootstrap:
    enabled: true
    namespaces: application,fp.jwt,fp.crypto
  autoUpdateInjectedSpringProperties: false
  meta: http://127.0.0.1:8080
  cluster: default

server:
  port: 8100
spring:
  profiles:
    active: dev #默认为开发环境

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.uzykj.fpsso: debug



mybatis:
  type-aliases-package: com.uzykj.fpadmin.mapper
  mapper-locations: classpath:mapper/*.xml